version:2
jobs:
    pre:
      steps:
        # Install the latest stable PlatformIO
        - run: sudo pip install -U platformio
        # preinstall esp8266 platform libs
        - run: platformio platform install espressif8266
    build:
      steps:
        - run: pio run -e native
    test:
      steps:
        - run: pio test -e native 
    flash:
      steps:
        - pio remote -a "remote-1" run -t upload

workflows:
  version: 2
  build_and_test:
    jobs:
      - pre
      - build
      - test
